version: '3'
services:
  my.server:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 1024M
    build:
      context: ./reactive-java17-server
    ports:
      - "8091:8091"
  my.client.1:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 1024M
    build:
      context: ./reactive-java17-client
    ports:
      - "8092:8092"
    environment:
      - "REACTIVE_SERVER_HOST=my.server"
    depends_on:
      - my.server
  my.client.2:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          memory: 1024M
    build:
      context: ./reactive-java17-client
    ports:
      - "8093:8092"
    environment:
      - "REACTIVE_SERVER_HOST=my.server"
    depends_on:
      - my.server